export const emprendimientos = [
  { nombre: "Pini", desc: "Artesanías en resina: llaveros, lapiceras, paletas nails, marcadores de páginas y más.", insta: "https://www.instagram.com/pini_creaciones1" },
  { nombre: "JJ iPhone", desc: "Reventa de iPhone usados y accesorios.", insta: "https://www.instagram.com/jj_iphone11" },
  { nombre: "Atenea MakeUp", desc: "Maquillaje profesional para eventos.", insta: "https://www.instagram.com/atenea_makeup12" },
  { nombre: "BAC", desc: "Venta de hamburguesas artesanales.", insta: "https://www.instagram.com/b.a.c_burger" },
  { nombre: "Titina", desc: "Indumentaria masculina y femenina.", insta: "https://www.instagram.com/ttitina.ind" },
  { nombre: "Aldonza", desc: "Venta de accesorios e indumentaria.", insta: "https://www.instagram.com/aldonza.showroom" },
  { nombre: "Stilos Magy", desc: "Ropa, accesorios y artículos varios.", insta: "https://www.instagram.com/stilos_magy" },
  { nombre: "Magnolia", desc: "Accesorios de acero quirúrgico.", insta: "https://www.instagram.com/magnoliaaceroquirurgico" },
  { nombre: "Mar de Tinta", desc: "Estudio de tatuajes profesionales.", insta: "https://www.instagram.com/mardetinta_tattoo" },
  { nombre: "JC Fotografías", desc: "Fotografía profesional para eventos.", insta: "https://www.instagram.com/jcfotografias91090" },
  { nombre: "El Sitio Comunicaciones", desc: "Tecnología y servicio técnico.", insta: "https://www.instagram.com/elsitiocomunicaciones" },
  { nombre: "Yeye Sublimaciones", desc: "Sublimados, cartelería y fly banner.", insta: "https://www.instagram.com/yeyesublimacionesok" },
  { nombre: "L-ístore", desc: "Venta de productos Apple usados y sellados.", insta: "https://www.instagram.com/ele.istore" },
  { nombre: "Regalería Lu", desc: "Bisutería, librería, moda y más.", insta: "https://www.instagram.com/reg_alerialu", fb: "https://www.facebook.com/share/1JMVNUHezU/" },
  { nombre: "Sense FastFood", desc: "Comida rápida y delivery.", fb: "https://www.facebook.com/share/19vTJsr44m/" },
  { nombre: "One_sport", desc: "Ropa deportiva y urbana.", insta: "https://www.instagram.com/one_sport0121" },
  { nombre: "VeeJay Be Glam", desc: "Maquillaje y belleza profesional.", insta: "https://www.instagram.com/veejay_byglam" },
  { nombre: "Forrajería Los Amigos", desc: "Alimentos y accesorios para mascotas.", insta: "https://www.instagram.com/forrajeria.los.amigos24" },
  { nombre: "Cóndor", desc: "Feria americana con ropa y accesorios.", insta: "https://www.instagram.com/condor.feriaamericana" },
  { nombre: "Cafetería Deli", desc: "Cafetería con postres y bebidas especiales.", insta: "https://www.instagram.com/cafeteria_deli" },
  { nombre: "Nam Teo", desc: "Accesorios y maquillaje.", insta: "https://www.instagram.com/namteo_" },
  { nombre: "Rocío Antonella", desc: "Manicuría profesional y estética.", insta: "https://www.instagram.com/gabinete_rocioantonella2023" },
  { nombre: "Ciamin", desc: "Accesorios variados para toda ocasión.", insta: "https://www.instagram.com/ciamin.ok" }
];
